//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileMatch.Services {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageService() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProfileMatch.Services.LanguageService", typeof(LanguageService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 1. You forgot your login or password.
        /// </summary>
        public static string _1__Zapomniałeś_loginu_lub_hasła {
            get {
                return ResourceManager.GetString("1. Zapomniałeś loginu lub hasła", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 2. You don&apos;t have an account.
        /// </summary>
        public static string _2__Nie_posiadasz_konta {
            get {
                return ResourceManager.GetString("2. Nie posiadasz konta", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 3. You cannot log in.
        /// </summary>
        public static string _3__Nie_możesz_się_zalogować {
            get {
                return ResourceManager.GetString("3. Nie możesz się zalogować", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Log out.
        /// </summary>
        public static string _Log_out {
            get {
                return ResourceManager.GetString(" Log out", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Activate question.
        /// </summary>
        public static string Activate_question {
            get {
                return ResourceManager.GetString("Activate question", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Certificate.
        /// </summary>
        public static string Add_Certificate {
            get {
                return ResourceManager.GetString("Add Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add New.
        /// </summary>
        public static string Add_New {
            get {
                return ResourceManager.GetString("Add New", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Question.
        /// </summary>
        public static string Add_Question {
            get {
                return ResourceManager.GetString("Add Question", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add User.
        /// </summary>
        public static string Add_User {
            get {
                return ResourceManager.GetString("Add User", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Admin Dashboard.
        /// </summary>
        public static string admindashboard {
            get {
                return ResourceManager.GetString("admindashboard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu already exists.
        /// </summary>
        public static string already_exists {
            get {
                return ResourceManager.GetString("already exists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Answer added.
        /// </summary>
        public static string Answer_added {
            get {
                return ResourceManager.GetString("Answer added", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Answer option created.
        /// </summary>
        public static string Answer_option_created {
            get {
                return ResourceManager.GetString("Answer option created", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Answer option updated.
        /// </summary>
        public static string Answer_option_updated {
            get {
                return ResourceManager.GetString("Answer option updated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Answer updated.
        /// </summary>
        public static string Answer_updated {
            get {
                return ResourceManager.GetString("Answer updated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Answer Option.
        /// </summary>
        public static string AnswerOption {
            get {
                return ResourceManager.GetString("AnswerOption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        public static string Anuluj {
            get {
                return ResourceManager.GetString("Anuluj", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Assigned:.
        /// </summary>
        public static string Assigned {
            get {
                return ResourceManager.GetString("Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Back to main site.
        /// </summary>
        public static string Back_to_main_site {
            get {
                return ResourceManager.GetString("Back to main site", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Birth Date.
        /// </summary>
        public static string Birth_Date {
            get {
                return ResourceManager.GetString("Birth Date", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu BirthDate is Required.
        /// </summary>
        public static string BirthDate_is_Required {
            get {
                return ResourceManager.GetString("BirthDate is Required", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bordered.
        /// </summary>
        public static string Bordered {
            get {
                return ResourceManager.GetString("Bordered", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cards.
        /// </summary>
        public static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category created.
        /// </summary>
        public static string Category_created {
            get {
                return ResourceManager.GetString("Category created", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category Description.
        /// </summary>
        public static string Category_Description {
            get {
                return ResourceManager.GetString("Category Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category Name.
        /// </summary>
        public static string Category_Name {
            get {
                return ResourceManager.GetString("Category Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category name is required!.
        /// </summary>
        public static string Category_name_is_required_ {
            get {
                return ResourceManager.GetString("Category name is required!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category updated.
        /// </summary>
        public static string Category_updated {
            get {
                return ResourceManager.GetString("Category updated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cert name.
        /// </summary>
        public static string Cert_name {
            get {
                return ResourceManager.GetString("Cert name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Certificate Name.
        /// </summary>
        public static string Certificate_Name {
            get {
                return ResourceManager.GetString("Certificate Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Certificates.
        /// </summary>
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose the question you want to answer.
        /// </summary>
        public static string Choose_the_question_you_want_to_answer {
            get {
                return ResourceManager.GetString("Choose the question you want to answer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Closed Question.
        /// </summary>
        public static string Closed_Question {
            get {
                return ResourceManager.GetString("Closed Question", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Closed Questions.
        /// </summary>
        public static string Closed_Questions {
            get {
                return ResourceManager.GetString("Closed Questions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Closed Questions Table.
        /// </summary>
        public static string Closed_Questions_Table {
            get {
                return ResourceManager.GetString("Closed Questions Table", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu created.
        /// </summary>
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date Of Birth.
        /// </summary>
        public static string Date_Of_Birth {
            get {
                return ResourceManager.GetString("Date Of Birth", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date of issue.
        /// </summary>
        public static string Date_of_issue {
            get {
                return ResourceManager.GetString("Date of issue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dense.
        /// </summary>
        public static string Dense {
            get {
                return ResourceManager.GetString("Dense", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Department Description.
        /// </summary>
        public static string Department_Description {
            get {
                return ResourceManager.GetString("Department Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Department Name.
        /// </summary>
        public static string Department_Name {
            get {
                return ResourceManager.GetString("Department Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Department name is required!.
        /// </summary>
        public static string Department_name_is_required_ {
            get {
                return ResourceManager.GetString("Department name is required!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit Answer.
        /// </summary>
        public static string Edit_Answer {
            get {
                return ResourceManager.GetString("Edit Answer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit Answer Level.
        /// </summary>
        public static string Edit_Answer_Level {
            get {
                return ResourceManager.GetString("Edit Answer Level", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit Category.
        /// </summary>
        public static string Edit_Category {
            get {
                return ResourceManager.GetString("Edit Category", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit Department.
        /// </summary>
        public static string Edit_Department {
            get {
                return ResourceManager.GetString("Edit Department", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit Level.
        /// </summary>
        public static string Edit_Level {
            get {
                return ResourceManager.GetString("Edit Level", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit openQuestion.
        /// </summary>
        public static string Edit_openQuestion {
            get {
                return ResourceManager.GetString("Edit openQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit Question.
        /// </summary>
        public static string Edit_Question {
            get {
                return ResourceManager.GetString("Edit Question", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit User.
        /// </summary>
        public static string Edit_User {
            get {
                return ResourceManager.GetString("Edit User", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Email is required!.
        /// </summary>
        public static string Email_is_required_ {
            get {
                return ResourceManager.GetString("Email is required!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter the email address linked to your account and you will recieve an email containing a link to reset your password..
        /// </summary>
        public static string Enter_the_email_address_linked_to_your_account_and_you_will_recieve_an_email_containing_a_link_to_reset_your_password_ {
            get {
                return ResourceManager.GetString("Enter the email address linked to your account and you will recieve an email cont" +
                        "aining a link to reset your password.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Forgot Password?.
        /// </summary>
        public static string Forgot_Password_ {
            get {
                return ResourceManager.GetString("Forgot Password?", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Full Name.
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu has been created.
        /// </summary>
        public static string has_been_created_F_ {
            get {
                return ResourceManager.GetString("has been created[F]", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu has been created.
        /// </summary>
        public static string has_been_created_M_ {
            get {
                return ResourceManager.GetString("has been created[M]", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu has been created.
        /// </summary>
        public static string has_been_created_O_ {
            get {
                return ResourceManager.GetString("has been created[O]", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu has been updated.
        /// </summary>
        public static string has_been_updated_F_ {
            get {
                return ResourceManager.GetString("has been updated[F]", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu has been updated.
        /// </summary>
        public static string has_been_updated_M_ {
            get {
                return ResourceManager.GetString("has been updated[M]", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu has been updated.
        /// </summary>
        public static string has_been_updated_O_ {
            get {
                return ResourceManager.GetString("has been updated[O]", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Password.
        /// </summary>
        public static string Hasło {
            get {
                return ResourceManager.GetString("Hasło", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hello.
        /// </summary>
        public static string Hell {
            get {
                return ResourceManager.GetString("Hell", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Welcome in Profile Match!.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hover.
        /// </summary>
        public static string Hover {
            get {
                return ResourceManager.GetString("Hover", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is a need.
        /// </summary>
        public static string Is_a_need {
            get {
                return ResourceManager.GetString("Is a need", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is Active.
        /// </summary>
        public static string Is_Active {
            get {
                return ResourceManager.GetString("Is Active", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is Active?.
        /// </summary>
        public static string Is_Active_ {
            get {
                return ResourceManager.GetString("Is Active?", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Items per page.
        /// </summary>
        public static string Items_per_page {
            get {
                return ResourceManager.GetString("Items per page", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Job Title.
        /// </summary>
        public static string Job_Title {
            get {
                return ResourceManager.GetString("Job Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu label.
        /// </summary>
        public static string label {
            get {
                return ResourceManager.GetString("label", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Level Description.
        /// </summary>
        public static string Level_Description {
            get {
                return ResourceManager.GetString("Level Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Level Description is required!.
        /// </summary>
        public static string Level_Description_is_required_ {
            get {
                return ResourceManager.GetString("Level Description is required!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu loading.
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Log out.
        /// </summary>
        public static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maintenance.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manager Dashboard.
        /// </summary>
        public static string Manager_Dashboard {
            get {
                return ResourceManager.GetString("Manager Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Max 20 characters.
        /// </summary>
        public static string Max_20_characters {
            get {
                return ResourceManager.GetString("Max 20 characters", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Max 200 characters.
        /// </summary>
        public static string Max_200_characters {
            get {
                return ResourceManager.GetString("Max 200 characters", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Max allowed size is 5MB.
        /// </summary>
        public static string Max_allowed_size_is_5MB {
            get {
                return ResourceManager.GetString("Max allowed size is 5MB", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Max length.
        /// </summary>
        public static string Max_length {
            get {
                return ResourceManager.GetString("Max length", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu My Categories.
        /// </summary>
        public static string My_Categories {
            get {
                return ResourceManager.GetString("My Categories", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu My hobbies.
        /// </summary>
        public static string My_hobbies {
            get {
                return ResourceManager.GetString("My hobbies", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu My other skills.
        /// </summary>
        public static string My_other_skills {
            get {
                return ResourceManager.GetString("My other skills", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Category.
        /// </summary>
        public static string New_Category {
            get {
                return ResourceManager.GetString("New Category", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Department.
        /// </summary>
        public static string New_Department {
            get {
                return ResourceManager.GetString("New Department", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New User.
        /// </summary>
        public static string New_User {
            get {
                return ResourceManager.GetString("New User", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Next people.
        /// </summary>
        public static string Next_people {
            get {
                return ResourceManager.GetString("Next people", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open Questions.
        /// </summary>
        public static string Open_Questions {
            get {
                return ResourceManager.GetString("Open Questions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Operation cancelled.
        /// </summary>
        public static string Operation_cancelled {
            get {
                return ResourceManager.GetString("Operation cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Describe your problem.
        /// </summary>
        public static string Opisz_swój_problem {
            get {
                return ResourceManager.GetString("Opisz swój problem", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu People Match.
        /// </summary>
        public static string People_Match {
            get {
                return ResourceManager.GetString("People Match", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Person name is required!.
        /// </summary>
        public static string Person_name_is_required_ {
            get {
                return ResourceManager.GetString("Person name is required!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Help.
        /// </summary>
        public static string Pomoc {
            get {
                return ResourceManager.GetString("Pomoc", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Profile Match.
        /// </summary>
        public static string Profile_Match {
            get {
                return ResourceManager.GetString("Profile Match", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Project Description.
        /// </summary>
        public static string Project_Description {
            get {
                return ResourceManager.GetString("Project Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Project Name.
        /// </summary>
        public static string Project_Name {
            get {
                return ResourceManager.GetString("Project Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Project name is required!.
        /// </summary>
        public static string Project_name_is_required_ {
            get {
                return ResourceManager.GetString("Project name is required!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please Log in.
        /// </summary>
        public static string Proszę_się_zalogować {
            get {
                return ResourceManager.GetString("Proszę się zalogować", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Question 1.
        /// </summary>
        public static string Question_1 {
            get {
                return ResourceManager.GetString("Question 1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Question 2.
        /// </summary>
        public static string Question_2 {
            get {
                return ResourceManager.GetString("Question 2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Question 3.
        /// </summary>
        public static string Question_3 {
            get {
                return ResourceManager.GetString("Question 3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Question 4.
        /// </summary>
        public static string Question_4 {
            get {
                return ResourceManager.GetString("Question 4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Question 5.
        /// </summary>
        public static string Question_5 {
            get {
                return ResourceManager.GetString("Question 5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Question already exists.
        /// </summary>
        public static string Question_already_exists_ {
            get {
                return ResourceManager.GetString("Question already exists.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Question created.
        /// </summary>
        public static string Question_created {
            get {
                return ResourceManager.GetString("Question created", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Question Description.
        /// </summary>
        public static string Question_Description {
            get {
                return ResourceManager.GetString("Question Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Question Name.
        /// </summary>
        public static string Question_Name {
            get {
                return ResourceManager.GetString("Question Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Question name is required!.
        /// </summary>
        public static string Question_name_is_required_ {
            get {
                return ResourceManager.GetString("Question name is required!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Question updated.
        /// </summary>
        public static string Question_updated {
            get {
                return ResourceManager.GetString("Question updated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reset Password.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset Password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Resource Administration.
        /// </summary>
        public static string Resource_Administration {
            get {
                return ResourceManager.GetString("Resource Administration", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Role Name:.
        /// </summary>
        public static string Role_Name {
            get {
                return ResourceManager.GetString("Role Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rows per page.
        /// </summary>
        public static string Rows_per_page {
            get {
                return ResourceManager.GetString("Rows per page", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save Changes.
        /// </summary>
        public static string Save_Changes {
            get {
                return ResourceManager.GetString("Save Changes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select All.
        /// </summary>
        public static string Select_All {
            get {
                return ResourceManager.GetString("Select All", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select all text.
        /// </summary>
        public static string Select_all_text {
            get {
                return ResourceManager.GetString("Select all text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select Category.
        /// </summary>
        public static string Select_Category {
            get {
                return ResourceManager.GetString("Select Category", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select Date of Birth.
        /// </summary>
        public static string Select_Date_of_Birth {
            get {
                return ResourceManager.GetString("Select Date of Birth", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select Department.
        /// </summary>
        public static string Select_Department {
            get {
                return ResourceManager.GetString("Select Department", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select Gender.
        /// </summary>
        public static string Select_Gender {
            get {
                return ResourceManager.GetString("Select Gender", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select Questions.
        /// </summary>
        public static string Select_Questions {
            get {
                return ResourceManager.GetString("Select Questions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select Users.
        /// </summary>
        public static string Select_Users {
            get {
                return ResourceManager.GetString("Select Users", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Selected Categories.
        /// </summary>
        public static string Selected_Categories {
            get {
                return ResourceManager.GetString("Selected Categories", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Selected items.
        /// </summary>
        public static string Selected_items {
            get {
                return ResourceManager.GetString("Selected items", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Selected Values.
        /// </summary>
        public static string Selected_Values {
            get {
                return ResourceManager.GetString("Selected Values", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Selection Page.
        /// </summary>
        public static string Selection_Page {
            get {
                return ResourceManager.GetString("Selection Page", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Set new password.
        /// </summary>
        public static string Set_new_password {
            get {
                return ResourceManager.GetString("Set new password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show profile.
        /// </summary>
        public static string Show_profile {
            get {
                return ResourceManager.GetString("Show profile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sign Up.
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sorry, there&apos;s nothing at this address..
        /// </summary>
        public static string Sorry__there_s_nothing_at_this_address_ {
            get {
                return ResourceManager.GetString("Sorry, there\'s nothing at this address.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sorry, this content is restricted..
        /// </summary>
        public static string Sorry__this_content_is_restricted_ {
            get {
                return ResourceManager.GetString("Sorry, this content is restricted.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sort By.
        /// </summary>
        public static string Sort_By {
            get {
                return ResourceManager.GetString("Sort By", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Striped.
        /// </summary>
        public static string Striped {
            get {
                return ResourceManager.GetString("Striped", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Surveys.
        /// </summary>
        public static string Surveys {
            get {
                return ResourceManager.GetString("Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There was an error.
        /// </summary>
        public static string There_was_an_error {
            get {
                return ResourceManager.GetString("There was an error", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This is my Level.
        /// </summary>
        public static string This_is_my_Level {
            get {
                return ResourceManager.GetString("This is my Level", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu unassigned.
        /// </summary>
        public static string unassigned {
            get {
                return ResourceManager.GetString("unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Upload file.
        /// </summary>
        public static string Upload_file {
            get {
                return ResourceManager.GetString("Upload file", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User Dashboard.
        /// </summary>
        public static string User_Dashboard {
            get {
                return ResourceManager.GetString("User Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User Name.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Welcome to the employee portal, select the tab you want to enter.
        /// </summary>
        public static string Welcome_to_the_employee_portal__select_the_tab_you_want_to_enter {
            get {
                return ResourceManager.GetString("Welcome to the employee portal, select the tab you want to enter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu What are my goals.
        /// </summary>
        public static string What_are_my_goals {
            get {
                return ResourceManager.GetString("What are my goals", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu What is important for me.
        /// </summary>
        public static string What_is_important_for_me {
            get {
                return ResourceManager.GetString("What is important for me", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu What is important to me at work.
        /// </summary>
        public static string What_is_important_to_me_at_work {
            get {
                return ResourceManager.GetString("What is important to me at work", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wrong file format. Allowed file formats are: .jpg, .jpeg, .png..
        /// </summary>
        public static string Wrong_file_format__Allowed_file_formats_are___jpg___jpeg___png_ {
            get {
                return ResourceManager.GetString("Wrong file format. Allowed file formats are: .jpg, .jpeg, .png.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose a topic.
        /// </summary>
        public static string Wybierz_temat {
            get {
                return ResourceManager.GetString("Wybierz temat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Send.
        /// </summary>
        public static string Wyślij {
            get {
                return ResourceManager.GetString("Wyślij", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You&apos;re not loggged in..
        /// </summary>
        public static string You_re_not_loggged_in_ {
            get {
                return ResourceManager.GetString("You\'re not loggged in.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You&apos;re not loggged in as Admin..
        /// </summary>
        public static string You_re_not_loggged_in_as_Admin_ {
            get {
                return ResourceManager.GetString("You\'re not loggged in as Admin.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You&apos;re not signed in as a user in Administration role..
        /// </summary>
        public static string You_re_not_signed_in_as_a_user_in__ADMINISTRATION_ROLE_role_ {
            get {
                return ResourceManager.GetString("You\'re not signed in as a user in @ADMINISTRATION_ROLE role.", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Log in.
        /// </summary>
        public static string Zaloguj {
            get {
                return ResourceManager.GetString("Zaloguj", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Remember.
        /// </summary>
        public static string Zapamiętaj {
            get {
                return ResourceManager.GetString("Zapamiętaj", resourceCulture);
            }
        }
    }
}
